Update README.md
In the docker network named minifab, the domain name .example.com should not use proxy. For example peer1.org0.example.com:7051.
Otherwise this will cause minifabric fails to install the avalon chaincode, and raise error information following:
```
Error: failed to retrieve endorser client for install: endorser client failed to connect to peer1.org0.example.com:7051: failed to create
 new connection: context deadline exceeded
```